### ISSUE TITLE
How do I get test result in the paper?

### ISSUE THREAD

**Issue by YangJae96** [chenhao2345/GCL#3]
I have trained and obtained your pretrained model,
how do I run the test result in the paper?

**Comment by chenhao2345** [comment]
In the main.py, we print test results after each epoch with `_, mAP_1 = evaluator_1.evaluate(test_loader_target, dataset_target.query, dataset_target.gallery, cmc_flag=True)`. You can find the ReID test results in the training log. You can also see your generated images with `tensorboard --logdir logs/market_init_JVTC_unsupervised/stage3/`.
